"""Viewer3DPanel — MuJoCo offscreen 3D viewer."""

from __future__ import annotations

import time
from typing import Any

import numpy as np
from PySide6.QtCore import Qt
from PySide6.QtGui import QImage, QPixmap
from PySide6.QtWidgets import QLabel, QVBoxLayout, QWidget

from jig.core.app_context import AppContext
from jig.panels.base import PanelBase
from jig.panels.registry import PanelRegistry

try:
    import mujoco

    HAS_MUJOCO = True
except ImportError:
    HAS_MUJOCO = False

ARM_MJCF = """\
<mujoco model="arm7">
  <option gravity="0 0 -9.81"/>
  <visual><global offwidth="640" offheight="480"/></visual>
  <worldbody>
    <light pos="0.5 -0.5 2" dir="-0.2 0.2 -1" diffuse="0.8 0.8 0.8"/>
    <light pos="-0.5 0.5 2" dir="0.2 -0.2 -1" diffuse="0.4 0.4 0.4"/>
    <geom type="plane" size="2 2 0.01" rgba="0.25 0.25 0.3 1"/>
    <body name="base" pos="0 0 0.05">
      <geom type="cylinder" size="0.08 0.05" rgba="0.3 0.3 0.35 1"/>
      <body name="link1" pos="0 0 0.05">
        <joint name="joint1" type="hinge" axis="0 0 1" range="-2.9 2.9"/>
        <geom type="capsule" fromto="0 0 0 0 0 0.333" size="0.045"
              rgba="0.9 0.9 0.95 1"/>
        <body name="link2" pos="0 0 0.333">
          <joint name="joint2" type="hinge" axis="0 1 0" range="-1.76 1.76"/>
          <geom type="capsule" fromto="0 0 0 0 0 0.316" size="0.045"
                rgba="0.85 0.85 0.9 1"/>
          <body name="link3" pos="0 0 0.316">
            <joint name="joint3" type="hinge" axis="0 0 1" range="-2.9 2.9"/>
            <geom type="capsule" fromto="0 0 0 0 0 0.083" size="0.04"
                  rgba="0.9 0.9 0.95 1"/>
            <body name="link4" pos="0 0 0.083">
              <joint name="joint4" type="hinge" axis="0 -1 0" range="-3.07 0.07"/>
              <geom type="capsule" fromto="0 0 0 0 0 0.384" size="0.04"
                    rgba="0.85 0.85 0.9 1"/>
              <body name="link5" pos="0 0 0.384">
                <joint name="joint5" type="hinge" axis="0 0 1" range="-2.9 2.9"/>
                <geom type="capsule" fromto="0 0 0 0 0 0.088" size="0.035"
                      rgba="0.9 0.9 0.95 1"/>
                <body name="link6" pos="0 0 0.088">
                  <joint name="joint6" type="hinge" axis="0 1 0" range="-0.02 3.75"/>
                  <geom type="capsule" fromto="0 0 0 0 0 0.107" size="0.035"
                        rgba="0.85 0.85 0.9 1"/>
                  <body name="link7" pos="0 0 0.107">
                    <joint name="joint7" type="hinge" axis="0 0 1" range="-2.9 2.9"/>
                    <geom type="cylinder" size="0.045 0.025" rgba="0.95 0.6 0.2 1"/>
                  </body>
                </body>
              </body>
            </body>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
</mujoco>
"""

# Joint series paths generated by mcap_reader for the default test data
_JOINT_SERIES = [f"/joint_states/position[{i}]" for i in range(7)]


@PanelRegistry.register
class Viewer3DPanel(PanelBase):
    panel_type_name = "3D Viewer"

    def __init__(self, ctx: AppContext, parent: QWidget | None = None) -> None:
        super().__init__(ctx, parent)
        self.setMinimumSize(320, 240)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._image_label = QLabel("3D Viewer")
        self._image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._image_label.setStyleSheet("background: #1a1a2e;")
        layout.addWidget(self._image_label, stretch=1)

        self._status_label = QLabel("")
        self._status_label.setStyleSheet("font-size: 11px; padding: 2px;")
        layout.addWidget(self._status_label)

        self._mj_ok = False
        self._last_mouse_pos = None

        if HAS_MUJOCO:
            try:
                self._init_mujoco()
                self._mj_ok = True
            except Exception as e:
                self._status_label.setText(f"MuJoCo init error: {e}")
        else:
            self._status_label.setText("mujoco not installed")

        self._render()

    def _init_mujoco(self) -> None:
        self._model = mujoco.MjModel.from_xml_string(ARM_MJCF)
        self._mj_data = mujoco.MjData(self._model)
        self._renderer = mujoco.Renderer(self._model, height=480, width=640)

        self._camera = mujoco.MjvCamera()
        self._camera.type = mujoco.mjtCamera.mjCAMERA_FREE
        self._camera.distance = 2.5
        self._camera.azimuth = 135.0
        self._camera.elevation = -25.0
        self._camera.lookat[:] = [0.0, 0.0, 0.6]

        self._scene_opt = mujoco.MjvOption()
        self._scene_opt.frame = mujoco.mjtFrame.mjFRAME_BODY

    def _render(self) -> None:
        if not self._mj_ok:
            return

        t0 = time.perf_counter()
        t = self.ctx.timeline.current_time
        ds = self.ctx.active_data_store

        if ds is not None:
            for i, path in enumerate(_JOINT_SERIES):
                if i < self._model.nq:
                    self._mj_data.qpos[i] = ds.get_scalar_at(path, t)

        mujoco.mj_forward(self._model, self._mj_data)
        self._renderer.update_scene(
            self._mj_data, camera=self._camera, scene_option=self._scene_opt
        )
        rgb = self._renderer.render()
        dt_ms = (time.perf_counter() - t0) * 1000

        h, w, _ = rgb.shape
        rgb_c = np.ascontiguousarray(rgb)
        qimg = QImage(rgb_c.data, w, h, 3 * w, QImage.Format.Format_RGB888)
        pixmap = QPixmap.fromImage(qimg.copy())

        self._image_label.setPixmap(
            pixmap.scaled(
                self._image_label.size(),
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation,
            )
        )
        self._status_label.setText(
            f"Render: {dt_ms:.1f} ms  ({1000 / max(dt_ms, 0.1):.0f} fps)"
        )

    # -- PanelBase interface -------------------------------------------------

    def on_time_changed(self, t: float) -> None:
        self._render()

    def get_state(self) -> dict[str, Any]:
        if not self._mj_ok:
            return {}
        return {
            "camera_distance": self._camera.distance,
            "camera_azimuth": self._camera.azimuth,
            "camera_elevation": self._camera.elevation,
            "camera_lookat": list(self._camera.lookat),
        }

    def set_state(self, state: dict[str, Any]) -> None:
        if not self._mj_ok or not state:
            return
        self._camera.distance = state.get("camera_distance", self._camera.distance)
        self._camera.azimuth = state.get("camera_azimuth", self._camera.azimuth)
        self._camera.elevation = state.get("camera_elevation", self._camera.elevation)
        lookat = state.get("camera_lookat")
        if lookat:
            self._camera.lookat[:] = lookat

    # -- Mouse orbit / pan / zoom -------------------------------------------

    def mousePressEvent(self, event) -> None:
        self._last_mouse_pos = event.position()

    def mouseMoveEvent(self, event) -> None:
        if self._last_mouse_pos is None or not self._mj_ok:
            return
        dx = event.position().x() - self._last_mouse_pos.x()
        dy = event.position().y() - self._last_mouse_pos.y()
        self._last_mouse_pos = event.position()

        if event.buttons() & Qt.MouseButton.LeftButton:
            self._camera.azimuth += dx * 0.5
            self._camera.elevation = float(
                np.clip(self._camera.elevation - dy * 0.5, -90, 90)
            )
            self._render()
        elif event.buttons() & Qt.MouseButton.RightButton:
            self._camera.lookat[0] -= dx * 0.003
            self._camera.lookat[2] += dy * 0.003
            self._render()

    def mouseReleaseEvent(self, event) -> None:
        self._last_mouse_pos = None

    def wheelEvent(self, event) -> None:
        if not self._mj_ok:
            return
        delta = event.angleDelta().y()
        self._camera.distance *= 1.0 - delta * 0.001
        self._camera.distance = max(0.1, self._camera.distance)
        self._render()
